### ISSUE TITLE
请求

### ISSUE THREAD

**Issue by pakhogo** [hedrox/ecg-classification#6]
您好，非常感谢您提供的资源，我想请您帮我调试您的程序，我是大四学生，python小白，还请求您可以给我稍微讲解您的程序哪个部分实现的功能。我愿意支付您酬劳，十分感谢。

**Comment by pakhogo** [comment]
Hello, thank you very much for your resources. I'd like to ask you to help me debug your program. I'm a senior, python Xiaobai. I also ask you to explain to me which part of your program realizes the function. I'd like to pay you. Thank you very much.

**Comment by hedrox** [comment]
Hello, I have updated the README file with the correct link to the wfdb tool. After you install the wfdb you can run fetch_data in order to download the datasets. The last part is running cnn_tf2.py that will train the neural network and evaluate it.
I will do a refactor and try to make things simpler in the future because at the moment I don't have enough time.
